# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from duckietown_msgs/StopLineReading.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class StopLineReading(genpy.Message):
  _md5sum = "55f653b3c7e032a4d334c48bf9dce3f5"
  _type = "duckietown_msgs/StopLineReading"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header
bool stop_line_detected
bool at_stop_line
float32 line_angle # the angle of the stop line normal relative to the bot
geometry_msgs/Point stop_line_point # this is in the "lane frame"

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['header','stop_line_detected','at_stop_line','line_angle','stop_line_point']
  _slot_types = ['std_msgs/Header','bool','bool','float32','geometry_msgs/Point']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,stop_line_detected,at_stop_line,line_angle,stop_line_point

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(StopLineReading, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.stop_line_detected is None:
        self.stop_line_detected = False
      if self.at_stop_line is None:
        self.at_stop_line = False
      if self.line_angle is None:
        self.line_angle = 0.
      if self.stop_line_point is None:
        self.stop_line_point = geometry_msgs.msg.Point()
    else:
      self.header = std_msgs.msg.Header()
      self.stop_line_detected = False
      self.at_stop_line = False
      self.line_angle = 0.
      self.stop_line_point = geometry_msgs.msg.Point()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2Bf3d().pack(_x.stop_line_detected, _x.at_stop_line, _x.line_angle, _x.stop_line_point.x, _x.stop_line_point.y, _x.stop_line_point.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.stop_line_point is None:
        self.stop_line_point = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 30
      (_x.stop_line_detected, _x.at_stop_line, _x.line_angle, _x.stop_line_point.x, _x.stop_line_point.y, _x.stop_line_point.z,) = _get_struct_2Bf3d().unpack(str[start:end])
      self.stop_line_detected = bool(self.stop_line_detected)
      self.at_stop_line = bool(self.at_stop_line)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2Bf3d().pack(_x.stop_line_detected, _x.at_stop_line, _x.line_angle, _x.stop_line_point.x, _x.stop_line_point.y, _x.stop_line_point.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.stop_line_point is None:
        self.stop_line_point = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 30
      (_x.stop_line_detected, _x.at_stop_line, _x.line_angle, _x.stop_line_point.x, _x.stop_line_point.y, _x.stop_line_point.z,) = _get_struct_2Bf3d().unpack(str[start:end])
      self.stop_line_detected = bool(self.stop_line_detected)
      self.at_stop_line = bool(self.at_stop_line)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_2Bf3d = None
def _get_struct_2Bf3d():
    global _struct_2Bf3d
    if _struct_2Bf3d is None:
        _struct_2Bf3d = struct.Struct("<2Bf3d")
    return _struct_2Bf3d
